@startuml

package Main <<Rect>> {
    object Hauptprogramm {
        Der Aufhängepunkt
        für das Programm
    }
    object Hilfetext {
        Bei Bedarf kann ein Hilfetext
        ausgegeben werden
    }
}

package Calculator <<Rect>> {
    object Term_stack {
        Eine geordnete Liste von
        Termbestandteilen
    }
    object Programmschleife {
        Eine Endlosschleife 
        fragt immer wieder nach
        einer Eingabe und arbeitet
        diese dann ab.
    }
    object Ausgabe {
        Die Ausgabe erfolgt auf
        der Konsole.
        Die Konsole wird
        dafür jedes Mal
        gelöscht und der
        Text erneut ausgegeben
    }
    object Eingabe {
        Die Eingabe erfolg
        auf der Konsole
        Es wird jedes Mal
        ein String eingelesen
        und verarbeitet
    }
}

package calc_model <<Rect>> {
    object Baumfactory {
        Diese weiß, wie der Term aus
        den Bestandteilen aufgebaut
        werden muss
    }
    object Termbaum{
        Der Baum spiegelt den eingegeben
        Term wieder und kann das Ergebnis
        der Gleichung ermitteln. Dies erfolgt
        rekursiv über seine Blätter und Äste
    }
}

Main .down.> Calculator
Calculator .down.> calc_model
@enduml
