@startuml

title "1 / 2 + 3 ** 4 * 5"

object add
object div
object multi
object 1
object 2
object exp
object 5
object 3
object 4


add <-- div
div <-- 1
div <-- 2
add <-- multi
multi <-- 5
multi <-- exp
exp <-- 3
exp <-- 4

@enduml
