@startuml

title "1 / 2 + 3 ** 4 * 5"

object add
object multi
object exp
object div
object 1
object 2
object 3
object 4
object 5

div -up-> add
1 -up-> div
2 -up-> div
multi -up-> add
5 -up-> multi
exp -up-> multi
3 -up-> exp
4 -up-> exp

@enduml
